version: "3.7"
services:

  database_super_price:
    image: postgres
    container_name: database_super_price
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$${process.env.POSTGRES_USER}
      - POSTGRES_PASSWORD=$${process.env.POSTGRES_PASSWORD}
      - POSTGRES_DB=$${process.env.POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api_super_price
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_super_price
    depends_on:
      - database_super_price

volumes:
  pgdata:
    driver: local
