version: "3.7"
services:

  super_price_database:
    image: postgres
    container_name: super_price_database
    restart: always
    ports:
      - 65432:5432
    env_file:
    - .env
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: super_price_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - super_price_database
    depends_on:
      - super_price_database

volumes:
  pgdata:
    driver: local
