version: "3.7"
services:

  super_price_database:
    image: postgres
    container_name: super_price_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=superprice
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: super_price_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - super_price_database
    depends_on:
      - super_price_database

volumes:
  pgdata:
    driver: local
